eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.112:8761/eureka/,http://192.168.0.112:8762/eureka/
env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.0.115:3306/sell_test
    username: root
  rabbitmq:
    host: 192.168.0.115
    port: 5672
    username: root
    password: 123456

password: '{cipher}68091c2cc2fc63c6f6ce742c2fa7163af787d7e89764954d673aedfa06fc229f'

testRefresh: root

gril:
  name: benko
  age: 179
